"""학생 원장 저장 경계."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ..shared.student_identity import StudentIdentity, StudentIdentityPage
from .models import Student


class StudentRepository(Protocol):
    def create(self, student: Student) -> Student: ...
    def get_student(self, student_id: str) -> Student | None: ...
    def list_students(self, *, limit: int, offset: int) -> list[Student]: ...
    def register_face(
        self, student_id: str, enrollment_id: str, updated_at: datetime
    ) -> Student | None: ...
    def unregister_face(self, student_id: str, updated_at: datetime) -> Student | None: ...
    def find_by_id(self, student_id: str) -> StudentIdentity | None: ...
    def list_active(self, *, limit: int, offset: int) -> StudentIdentityPage: ...
