"""얼굴 등록의 프로세스 외부 I/O 경계."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import FaceAnalysis, FaceEnrollment, FaceProfile, FaceSampleMetadata


class FaceEnrollmentRepository(Protocol):
    def create(self, enrollment: FaceEnrollment) -> FaceEnrollment: ...
    def get(self, enrollment_id: str) -> FaceEnrollment | None: ...
    def get_active(self) -> FaceEnrollment | None: ...
    def replace(self, enrollment: FaceEnrollment) -> FaceEnrollment: ...
    def delete(self, enrollment_id: str) -> None: ...
    def get_profile(self, student_id: str) -> FaceProfile | None: ...
    def save_profile(self, profile: FaceProfile) -> FaceProfile: ...
    def delete_profile(self, student_id: str) -> None: ...


class FaceObjectStorage(Protocol):
    def prepare_enrollment(
        self, enrollment_id: str, student_id: str, created_at: datetime
    ) -> None: ...
    def put_sample(
        self, enrollment_id: str, metadata: FaceSampleMetadata, content: bytes
    ) -> None: ...
    def finalize_dataset(
        self, enrollment_id: str, student_id: str, augmented_sample_count: int
    ) -> None: ...
    def delete_enrollment(self, enrollment_id: str) -> None: ...


class FaceAnalyzer(Protocol):
    def analyze(self, enrollment_id: str, frame: bytes) -> FaceAnalysis: ...
    def finalize(self, enrollment_id: str) -> str: ...
    def discard(self, enrollment_id: str) -> None: ...
