"""Repository port for classroom and seat persistence."""

from __future__ import annotations

from datetime import date, datetime
from typing import Protocol

from .models import (
    AfterHoursAlert,
    AfterHoursAlertPage,
    AfterHoursAlertStatus,
    Classroom,
    ClassroomPage,
    Seat,
    SeatObservationBatchRecord,
    SeatOccupancyHistory,
    SeatOccupancyHistoryPage,
    SeatPage,
)


class ClassroomRepository(Protocol):
    def create_classroom(self, classroom: Classroom) -> Classroom: ...
    def get_classroom(self, classroom_id: str) -> Classroom | None: ...
    def get_classroom_by_code(self, code: str) -> Classroom | None: ...
    def get_classroom_by_operation_id(self, operation_id: str) -> Classroom | None: ...
    def list_classrooms(self, *, include_inactive: bool, limit: int, offset: int) -> ClassroomPage: ...
    def replace_classroom(self, classroom: Classroom, *, expected_version: int) -> Classroom | None: ...

    def create_seat(self, seat: Seat) -> Seat: ...
    def get_seat(self, seat_id: str) -> Seat | None: ...
    def get_seat_by_operation_id(self, operation_id: str) -> Seat | None: ...
    def list_seats(self, classroom_id: str, *, include_inactive: bool, limit: int, offset: int) -> SeatPage: ...
    def replace_seat(self, seat: Seat, *, expected_version: int) -> Seat | None: ...

    def claim_observation_batch(self, record: SeatObservationBatchRecord) -> SeatObservationBatchRecord: ...
    def get_observation_batch(self, event_id: str) -> SeatObservationBatchRecord | None: ...
    def complete_observation_batch(self, record: SeatObservationBatchRecord) -> SeatObservationBatchRecord: ...
    def get_history_by_event_and_seat(self, event_id: str, seat_id: str) -> SeatOccupancyHistory | None: ...
    def append_occupancy_history(self, history: SeatOccupancyHistory) -> SeatOccupancyHistory: ...
    def list_occupancy_history(
        self,
        classroom_id: str,
        *,
        seat_id: str | None,
        from_time: datetime | None,
        to_time: datetime | None,
        limit: int,
        offset: int,
    ) -> SeatOccupancyHistoryPage: ...

    def create_alert(self, alert: AfterHoursAlert) -> tuple[AfterHoursAlert, bool]: ...
    def get_alert(self, alert_id: str) -> AfterHoursAlert | None: ...
    def get_alert_by_operation_id(self, operation_id: str) -> AfterHoursAlert | None: ...
    def list_alerts(
        self,
        *,
        status: AfterHoursAlertStatus | None,
        classroom_id: str | None,
        business_date: date | None,
        limit: int,
        offset: int,
    ) -> AfterHoursAlertPage: ...
    def replace_alert(self, alert: AfterHoursAlert, *, expected_version: int) -> AfterHoursAlert | None: ...
