"""강의실과 좌석 metadata 저장소 포트."""

from __future__ import annotations

from typing import Protocol

from .models import (
    Classroom,
    ClassroomPage,
    Seat,
    SeatAssignment,
    SeatObservationBatchRecord,
    SeatOccupancyHistory,
    SeatPage,
)


class ClassroomRepository(Protocol):
    def create_classroom(self, classroom: Classroom) -> Classroom: ...
    def get_classroom(self, classroom_id: str) -> Classroom | None: ...
    def get_classroom_by_code(self, code: str) -> Classroom | None: ...
    def list_classrooms(self, *, limit: int, offset: int) -> ClassroomPage: ...
    def update_classroom(self, classroom: Classroom) -> Classroom: ...
    def delete_classroom(self, classroom_id: str) -> None: ...

    def create_seat(self, seat: Seat) -> Seat: ...
    def get_seat(self, seat_id: str) -> Seat | None: ...
    def list_seats(self, classroom_id: str, *, limit: int, offset: int) -> SeatPage: ...
    def update_seat(self, seat: Seat, *, unset_fields: list[str] | None = None) -> Seat: ...
    def delete_seat(self, seat_id: str) -> None: ...
    def replace_seat(self, seat: Seat, *, expected_version: int) -> Seat | None: ...

    def claim_observation_batch(
        self, record: SeatObservationBatchRecord
    ) -> SeatObservationBatchRecord: ...
    def get_observation_batch(self, event_id: str) -> SeatObservationBatchRecord | None: ...
    def complete_observation_batch(
        self, record: SeatObservationBatchRecord
    ) -> SeatObservationBatchRecord: ...
    def get_history_by_event_and_seat(
        self, event_id: str, seat_id: str
    ) -> SeatOccupancyHistory | None: ...
    def append_occupancy_history(self, history: SeatOccupancyHistory) -> SeatOccupancyHistory: ...


class SeatAssignmentRepository(Protocol):
    """좌석-학생 지정 저장소 추상화."""

    def assign(self, assignment: SeatAssignment) -> SeatAssignment:
        """학생을 좌석에 지정한다."""
        ...

    def unassign(self, seat_id: str) -> None:
        """좌석-학생 지정을 해제한다."""
        ...

    def get_by_seat(self, seat_id: str) -> SeatAssignment | None:
        """좌석 ID로 지정을 조회한다."""
        ...

    def get_by_student(self, student_id: str, classroom_id: str) -> SeatAssignment | None:
        """학생 ID와 강의실 ID로 지정을 조회한다."""
        ...

    def list_by_classroom(self, classroom_id: str) -> list[SeatAssignment]:
        """강의실의 모든 지정을 조회한다."""
        ...

    def unassign_by_student(self, student_id: str) -> int:
        """학생의 모든 좌석 지정을 해제한다. 해제된 지정 수를 반환한다."""
        ...
